language: node_js
node_js:
- '8'

before_install: "if [[ \"$TRAVIS_PULL_REQUEST\" = \"false\" ]]; then openssl aes-256-cbc -K $encrypted_1455fc9ea2db_key -iv $encrypted_1455fc9ea2db_iv -in serverless.env.yml.enc -out src/serverless.env.yml -d; fi"

after_success:
 - test $TRAVIS_BRANCH = "develop" && serverless deploy --stage staging
 # - test $TRAVIS_BRANCH = "master" && serverless deploy --stage prod
