service: cla-bot

resources:
  Resources:
    S3BucketPhotos:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(./src/serverless.env.yml):${opt:stage}.LOGGING_BUCKET}

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${file(./src/serverless.env.yml):${opt:stage}.LOGGING_BUCKET}/*"

functions:
  cla-bot:
    handler: src/index.handler
    environment: ${file(./src/serverless.env.yml):${opt:stage}}
    events:
      - http:
          path: cla-check
          method: post